org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=true
org.gradle.parallel=true

mod_id=vidlib
archives_base_name=vidlib
mod_name=VidLib
maven_group=dev.latvian.mods
mod_author=latvian.dev

mod_version=2601.1.0

neoforge_version=26.1.2.87
minecraft_version=26.1.2
klib_version=2601.1.2-build.152
bat_version=2601.1.0-build.8
geckolib_version=5.5.1
imgui_resources_version=1.0.2
tiny_http_version=1.0.0-build.59
simple_voice_chat_version=neoforge-2.6.18+26.1.2
iris_version=1.10.9+26.1-neoforge
